# Generated by Django 3.1.7 on 2021-02-21 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='pendings',
            field=models.ManyToManyField(blank=True, related_name='pending_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='rejected',
            field=models.ManyToManyField(blank=True, related_name='rejected_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
