<<<<<<< Updated upstream
# Generated by Django 3.1.6 on 2021-02-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
            ],
        ),
    ]
=======
# Generated by Django 3.1.7 on 2021-02-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
            ],
        ),
    ]
>>>>>>> Stashed changes
