# Generated by Django 3.1.6 on 2021-02-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tag_str',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='myApp.Tag'),
        ),
    ]
