# Generated by Django 3.1.6 on 2021-02-22 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 22, 14, 28, 53, 887846, tzinfo=utc), null=True),
        ),
    ]
