# Generated by Django 3.1.6 on 2021-02-17 06:23

from django.db import migrations, models
import myApp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to=myApp.utils.uuid_name_upload_to),
        ),
    ]
