# Generated by Django 2.0.13 on 2021-02-08 14:04

from django.db import migrations
import myApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', myApp.models.UserManager()),
            ],
        ),
    ]
