# Generated by Django 3.1.6 on 2021-02-23 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='tag_like_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='tag_save_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reference',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='reference_like_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reference',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='reference_save_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reference',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='references', to='myApp.Tag'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='portfolio_like_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='portfolio_save_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='myApp.Tag'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='place.location'),
        ),
        migrations.AddField(
            model_name='place',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='save_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='places', to='myApp.Tag'),
        ),
        migrations.AddField(
            model_name='place',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='images',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_images', to='myApp.contact'),
        ),
        migrations.AddField(
            model_name='images',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='myApp.portfolio'),
        ),
        migrations.AddField(
            model_name='images',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='myApp.reference'),
        ),
        migrations.AddField(
            model_name='images',
            name='with_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='with_artist_images', to='myApp.collaborationwithbrand'),
        ),
        migrations.AddField(
            model_name='images',
            name='with_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='with_brand_images', to='myApp.collaborationwithbrand'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='place.location'),
        ),
        migrations.AddField(
            model_name='contact',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='contact_save_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='myApp.Tag'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_comments', to='myApp.contact'),
        ),
        migrations.AddField(
            model_name='comment',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_comments', to='myApp.portfolio'),
        ),
        migrations.AddField(
            model_name='comment',
            name='with_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='with_artist_comments', to='myApp.collaborationwithbrand'),
        ),
        migrations.AddField(
            model_name='comment',
            name='with_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='with_brand_comments', to='myApp.collaborationwithbrand'),
        ),
        migrations.AddField(
            model_name='collaborationwithbrand',
            name='location',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='place.location'),
        ),
        migrations.AddField(
            model_name='collaborationwithbrand',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='with_brand_save_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationwithbrand',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='with_brand', to='myApp.Tag'),
        ),
        migrations.AddField(
            model_name='collaborationwithbrand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='with_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationwithartist',
            name='location',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='place.location'),
        ),
        migrations.AddField(
            model_name='collaborationwithartist',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='with_artist_save_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationwithartist',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='with_artists', to='myApp.Tag'),
        ),
        migrations.AddField(
            model_name='collaborationwithartist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='with_artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
