# Generated by Django 3.1.7 on 2021-02-22 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import myApp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myApp.utils.uuid_name_upload_to, verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=None, max_length=15, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2021, 2, 22, 12, 41, 56, 183372, tzinfo=utc), null=True)),
                ('post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_counts', to='myApp.portfolio')),
            ],
        ),
    ]
