# Generated by Django 3.1.5 on 2021-02-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210204_0055'),
        ('myApp', '0002_auto_20210204_1043'),
    ]

    operations = [
    ]
