# Generated by Django 3.1.6 on 2021-02-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210204_1043'),
        ('myApp', '0002_auto_20210204_0055'),
    ]

    operations = [
    ]
