# Generated by Django 3.1.7 on 2021-02-22 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210222_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 22, 14, 10, 52, 222200, tzinfo=utc), null=True),
        ),
    ]
