# Generated by Django 3.1.6 on 2021-02-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210211_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_comments', to='myApp.contact'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_comments', to='myApp.portfolio'),
        ),
        migrations.AlterField(
            model_name='image',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_images', to='myApp.contact'),
        ),
        migrations.AlterField(
            model_name='image',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='myApp.portfolio'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='myApp.contact'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_tags', to='myApp.portfolio'),
        ),
    ]
