# Generated by Django 3.1.6 on 2021-02-04 03:19

from django.db import migrations, models
import myApp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_merge_20210204_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=myApp.utils.uuid_name_upload_to),
        ),
    ]
