# Generated by Django 3.1.6 on 2021-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210217_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tag_str',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='myApp.Tag'),
        ),
    ]
