# Generated by Django 3.1.7 on 2021-02-22 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210222_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 22, 12, 45, 42, 9508, tzinfo=utc), null=True),
        ),
    ]
