# Generated by Django 3.1.5 on 2021-02-06 02:18

from django.db import migrations, models
import myApp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210206_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user.png', upload_to=myApp.utils.uuid_name_upload_to),
        ),
    ]
