# Generated by Django 3.1.6 on 2021-02-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210211_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_comments', to='myApp.contact'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_comments', to='myApp.portfolio'),
        ),
    ]
