# Generated by Django 3.1.7 on 2021-02-22 12:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210222_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 22, 12, 51, 29, 307524, tzinfo=utc), null=True),
        ),
    ]
