# Generated by Django 3.1.6 on 2021-02-04 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_user_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='save_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
