# Generated by Django 3.1.6 on 2021-02-06 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20210206_1118'),
        ('myApp', '0008_auto_20210206_0857'),
        ('myApp', '0003_merge_20210204_1422'),
    ]

    operations = [
    ]
